### ISSUE TITLE
[Feature request] Retrieve events

### ISSUE THREAD

**Issue by koalive** [iankloo/sigmaNet#1]
Dear Ian Kloo,

First, thanks a lot for your package. So far no htmlwidgets proposed OpenGL graph visualization and therefore none was suitable for big biological networks.
A nice addition would be to offer a way to retrieve nodes hovered or clicked by the user inside of the Shiny environment, in similar way as Plotly's *event_data* method. 
This should be technically doable since Sigma.js allows to bind callbacks to event.
I would be glad to give it a try myself later, but I am by no mean a JavaScript veteran, so it might take some time and I cannot guarantee an optimal solution...

Best regards.

**Comment by iankloo** [comment]
Thanks, this is a good idea.  Adding to the to do list.
