### ISSUE TITLE
addNodeSize() changes undirected network to directed network

### ISSUE THREAD

**Issue by aj2duncan** [iankloo/sigmaNet#11]
### Actual Behavior
addNodeSize() changes undirected network to directed network which means that some of the calculations may be incorrect. I found it from the betweenness values. 

Apologies, I somehow forgot to file an issue before filing a pr.

### Expected/Desired Behavior
Keep the network as undirected.

### How to Reproduce
See #10

**Comment by iankloo** [comment]
Good call!  Thanks for catching that.

Also, adding an issue to support directed graphs.  I'm working out the whole arrow/custom edge shape thing in Sigma before launching into the R plugin.
