### ISSUE TITLE
sigmaNetOutput displays locally but not on server

### ISSUE THREAD

**Issue by camraynor** [iankloo/sigmaNet#14]
Hi,

First, thank you for creating this excellent package. I've been working on a Shiny app that uses a graph generated with `sigmaNetOutput`. The graph displays when Shiny is running locally through RStudio, however, nothing appears when it is run from my server. Further, the shiny-server error logs show no errors. I run into the same problem when trying to host the example from the documentation. 

### Actual Behavior

This is the code I am running:

```
library(tidyverse)
library(shiny)
library(sigmaNet)

data(lesMis)

ui <- fluidPage(
  sigmaNetOutput('network', height = '600px'),
  textOutput('text')
)

server <- function(input, output, session) {
  output$text <- renderText({
    req(input$node_data)
    paste0('You clicked on: ', input$node_data$label)
  })
  
  output$network <- renderSigmaNet({
    sigmaNet::sigmaFromIgraph(lesMis) %>%
      addNodeLabels(labelAttr = 'label') %>%
      addListener('clickNode')
  })
}

shinyApp(ui = ui, server = server)
```

Here is how it displays on the server:

![image](https://user-images.githubusercontent.com/30672037/39598213-00743642-4ed5-11e8-8f40-c596d761926f.png)
http://data.camraynor.io/test/

### Expected/Desired Behavior

Here is how the Shiny app displays when running locally:

![networkexample](https://user-images.githubusercontent.com/30672037/39598260-3025f8ee-4ed5-11e8-93ab-a8ae06a3fcf9.PNG)

### How to Reproduce

When I check my server logs, everything seems to be running fine:

```
── Attaching packages ─────────────────────────────────────── tidyverse 1.2.1 ──
✔ ggplot2 2.2.1     ✔ purrr   0.2.4
✔ tibble  1.4.2     ✔ dplyr   0.7.4
✔ tidyr   0.8.0     ✔ stringr 1.2.0
✔ readr   1.1.1     ✔ forcats 0.3.0
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

Listening on http://127.0.0.1:35739
```
shiny-server.log
```
[2018-05-03T18:27:49.350] [INFO] shiny-server - Starting listener on 127.0.0.1:3838
```
All packages are up to date, and my server is running on an AWS EC2 t2.xlarge instance, which should have plenty of memory.

Any suggestions would be greatly appreciated.

**Comment by iankloo** [comment]
Cam,

I'll do a little more digging when I get a chance, but my first thought is to make sure the version of the package being used by Shiny Server is up-to-date with the version you're using in Rstudio.  I've run into issues in the past from differences between the package libraries being used by Rstudio and Shiny Server.

More to come though.

Thanks for pointing this out.

-Ian

**Comment by camraynor** [comment]
Ian,

Thank you for the helpful suggestion. I went through and made sure all my installations and packages are up to date. Unfortunately, the issue persists. I've included the version information below:

Local R version:

```
R version 3.4.4 (2018-03-15) -- "Someone to Lean On"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)
```

Server R version:

```
Package: r-base
Status: install ok installed
Priority: optional
Section: gnu-r
Installed-Size: 59
Maintainer: Dirk Eddelbuettel <edd@debian.org>
Architecture: all
Version: 3.4.4-1xenial0
Depends: r-base-core (>= 3.4.4-1xenial0), r-recommended (= 3.4.4-1xenial0)
Recommends: r-base-html, r-doc-html
Suggests: ess, r-doc-info | r-doc-pdf
```

Shiny Server version:

```
Package: shiny-server
Versions:
1.5.7.907 (/var/lib/dpkg/status)
Reverse Depends:
Dependencies:
1.5.7.907 - libc6 (2 2.7) r-base (2 2.15.1)
Provides:
1.5.7.907 -
Reverse Provides:
```

Local package versions:
```
> packageVersion("sigmaNet")
[1] ‘1.1.0’
> packageVersion("tidyverse")
[1] ‘1.2.1’
> packageVersion("shiny")
[1] ‘1.0.5’
```
Server package versions:
```
> packageVersion(c('sigmaNet'))
[1] ‘1.1.0’
> packageVersion(c('tidyverse'))
[1] ‘1.2.1’
> packageVersion(c('shiny'))
[1] ‘1.0.5’
```

**Comment by camraynor** [comment]
Update:

I checked my browser's Javascript console and found the following error message:

```
Uncaught Error: Invalid robust-message, no msg-id found
    at MessageReceiver.receive (shiny-server-client.min.js:1)
    at BufferedResendConnection._handleMessage (shiny-server-client.min.js:1)
    at RobustConnection._handleMessage (shiny-server-client.min.js:1)
    at y.conn.(/test/anonymous function) [as onmessage] (http://data.camraynor.io/test/__assets__/shiny-server-client.min.js:2:12002)
    at y.d.dispatchEvent (sockjs-0.3.4.min.js:27)
    at y._dispatchMessage (sockjs-0.3.4.min.js:27)
    at y._didMessage (sockjs-0.3.4.min.js:27)
    at WebSocket.e.ws.onmessage (sockjs-0.3.4.min.js:27)
```

[This tread](https://github.com/rstudio/shiny-server/issues/286) documents a similar error with a different R package, which, unfortunately, remains unresolved.

**Comment by koalive** [comment]
Hi Cam,

Are you using the same web browser to display the graphs locally and from your server? Themes are different on your screenshots, and I already observed some htmlwidgets not being rendered on older versions of Firefox / Chrome.

Best regards.

**Comment by camraynor** [comment]
Hi Vulliard,

Thank you for the suggestion. I'm using the latest version of Google Chrome in both cases, and the problem persists. 

![image](https://user-images.githubusercontent.com/30672037/39713824-61a0d6ce-51e5-11e8-85ff-c2b0ffd09df5.png)

Cam

**Comment by iankloo** [comment]
@camraynor Are you still having trouble with this?  I can't reproduce and haven't heard from anyone else with the issue.  Happy to help, but will need a reproducible example.  Otherwise, I can close down the issue to clean things up.

**Comment by camraynor** [comment]
@iankloo I've yet to get this working on my server, although it works nicely locally and it does seem to be working for others.

**Comment by MagisterFleisher** [comment]
I've been having precisely the same issue.  I had a similar problem with threejs.  I don't know what changed, but it started working recently.

I noticed that in my browser's console

```
VM2320:20 Uncaught TypeError: Cannot redefine property: BetterJsPop
    at Function.defineProperty (<anonymous>)
    at inject (<anonymous>:20:10)
    at <anonymous>:510:11
    at <anonymous>:511:11
```

``````
shiny-server-client.min.js:1 Uncaught Error: Invalid robust-message, no msg-id found
    at MessageReceiver.receive (shiny-server-client.min.js:1)
    at BufferedResendConnection._handleMessage (shiny-server-client.min.js:1)
    at RobustConnection._handleMessage (shiny-server-client.min.js:1)
    at y.conn.(:3838/samples/anonymous function) [as onmessage] (http://10.5.111.196:3838/samples/__assets__/shiny-server-client.min.js:2:12002)
    at y.d.dispatchEvent (sockjs-0.3.4.min.js:27)
    at y._dispatchMessage (sockjs-0.3.4.min.js:27)
    at y._didMessage (sockjs-0.3.4.min.js:27)
    at WebSocket.e.ws.onmessage (sockjs-0.3.4.min.js:27)
```

**Comment by edwindj** [comment]
I had the same issue and traced it back to this fix https://github.com/rstudio/shiny-server-client/commit/29471965ecacded757605343fb8aee98e6e50491  (on March 27, 2017). If the json payload contained a newline, shiny-server did not parse it. Seems to be fixed.

**Comment by camraynor** [comment]
This appears to be resolved with the new shiny-server-client.
