### ISSUE TITLE
Max no of nodes

### ISSUE THREAD

**Issue by ksmvsn** [iankloo/sigmaNet#8]
Hi,

what is maximum no of nodes that can represented using sigmaNet for network visualization

**Comment by iankloo** [comment]
There is no maximum graph size for sigmaNet.  You will ultimately be constrained by your own computing resources, but there is no hard ceiling on the number of nodes/edges you can draw with Sigma.js (the underlying technology).  For example, if you are using a browser that supports Webgl (most modern browsers), you will be using your GPU to render the graph.  If you have a huge GPU, then you will be able to render a huge graph.

From the R side of things, there is nothing particularly computationally intensive going on behind the scenes, so if you can make an igraph object from your data, R will not have a problem creating the sigmaNet visualization.  From there, your constraint is on the browser/client that is rendering the graph (see the comment above).

With that said, this package was built to support larger graphs than the existing graph visualization capabilities in R.  When compared to D3.js and vis.js (and their R libraries), Sigma.js is a much better choice for large graph rendering. 

See this vignette for more info: https://iankloo.github.io/sigmaNet/articles/getting-started.html.
